
package menuk;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import ventanas.*;
import Cuestionario.*;


        
public class Interface extends javax.swing.JFrame {

  public void validarEx(){
    File file=new File("Inscripcion.txt");
    if(file.exists()){
    Examen.setEnabled(true);
    }

}
   public void ValidarAs(){
    File file=new File("Estudiantes.txt");
    if(file.exists()){
    AspiranteDan.setEnabled(true);
    }
  }
    public Interface() {
            initComponents();
            setLocationRelativeTo(null);
            setResizable(false);
            setTitle("Interface");
            setIconImage(new ImageIcon(getClass().getResource("/imagenes/Icono.PNG")).getImage());
        /*((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/karateFondo.jpg"));
        JLabel fondo=new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());*/
        Examen.setEnabled(false);
        validarEx();
        AspiranteDan.setEnabled(false);
        ValidarAs();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JPG = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Registro = new javax.swing.JMenu();
        Estudiantes = new javax.swing.JMenuItem();
        Instructor = new javax.swing.JMenuItem();
        Inscripcion = new javax.swing.JMenu();
        AspiranteDan = new javax.swing.JMenuItem();
        CRequisitor = new javax.swing.JMenuItem();
        Examen = new javax.swing.JMenuItem();
        Cuestionario = new javax.swing.JMenu();
        cinnegro = new javax.swing.JMenuItem();
        primerdan = new javax.swing.JMenuItem();
        segundodan = new javax.swing.JMenuItem();
        tercerdan = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cnegro = new javax.swing.JMenuItem();
        pdan = new javax.swing.JMenuItem();
        sdan = new javax.swing.JMenuItem();
        tdan = new javax.swing.JMenuItem();
        abriCues = new javax.swing.JMenu();
        buscar = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIVOK");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Academia de Karate Madrileña");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(40, 40, 40))
        );

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        JPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel3.setText("Bienvenido al Sistema Integrado de la Federacion Madrileña de Karate");

        Registro.setText("Registro ");

        Estudiantes.setText("Estudiantes");
        Estudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudiantesActionPerformed(evt);
            }
        });
        Registro.add(Estudiantes);

        Instructor.setText("Instructor");
        Instructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructorActionPerformed(evt);
            }
        });
        Registro.add(Instructor);

        jMenuBar1.add(Registro);

        Inscripcion.setText("Inscripcion");

        AspiranteDan.setText("Aspirante a Dan");
        AspiranteDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AspiranteDanActionPerformed(evt);
            }
        });
        Inscripcion.add(AspiranteDan);

        CRequisitor.setText("Requisitos Dan");
        CRequisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRequisitorActionPerformed(evt);
            }
        });
        Inscripcion.add(CRequisitor);

        Examen.setText("Examen");
        Examen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamenActionPerformed(evt);
            }
        });
        Inscripcion.add(Examen);

        jMenuBar1.add(Inscripcion);

        Cuestionario.setText("Cuestionario");

        cinnegro.setText("Cinturon negro");
        cinnegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinnegroActionPerformed(evt);
            }
        });
        Cuestionario.add(cinnegro);

        primerdan.setText("Primer DAN");
        primerdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primerdanActionPerformed(evt);
            }
        });
        Cuestionario.add(primerdan);

        segundodan.setText("Segundo DAN");
        segundodan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundodanActionPerformed(evt);
            }
        });
        Cuestionario.add(segundodan);

        tercerdan.setText("Tercer DAN");
        tercerdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tercerdanActionPerformed(evt);
            }
        });
        Cuestionario.add(tercerdan);

        jMenuBar1.add(Cuestionario);

        jMenu2.setText("Crear Prueba");

        cnegro.setText("Cinturon Negro");
        cnegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnegroActionPerformed(evt);
            }
        });
        jMenu2.add(cnegro);

        pdan.setText("Primer DAN");
        pdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdanActionPerformed(evt);
            }
        });
        jMenu2.add(pdan);

        sdan.setText("Segundo DAN");
        sdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdanActionPerformed(evt);
            }
        });
        jMenu2.add(sdan);

        tdan.setText("Tercer DAN");
        tdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdanActionPerformed(evt);
            }
        });
        jMenu2.add(tdan);

        jMenuBar1.add(jMenu2);

        abriCues.setText("Abrir Nueva Prueba");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        abriCues.add(buscar);

        jMenuBar1.add(abriCues);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel2)
                .addGap(71, 71, 71)
                .addComponent(JPG)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JPG)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudiantesActionPerformed
       
       // TODO add your handling code here:
        VentanaEstudiante sc= new VentanaEstudiante();
        sc.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_EstudiantesActionPerformed

    private void ExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamenActionPerformed
        VentanaExamen ot= new VentanaExamen();
        ot.setVisible(true);

        this.setVisible(false);
       
    }//GEN-LAST:event_ExamenActionPerformed

    private void InstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructorActionPerformed
        // TODO add your handling code here:
        VentanaInstructor A=new VentanaInstructor();
        A.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_InstructorActionPerformed

    private void AspiranteDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AspiranteDanActionPerformed
        // TODO add your handling code here:
        VentanaInscripcion A=new VentanaInscripcion();
        A.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_AspiranteDanActionPerformed

    private void CRequisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRequisitorActionPerformed
      
        Licencias A = null;
      try {
          A = new Licencias();
      } catch (FileNotFoundException ex) {
          Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
      }
        A.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_CRequisitorActionPerformed

    private void cnegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnegroActionPerformed
        Pregunt p=new Pregunt();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cnegroActionPerformed

    private void pdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdanActionPerformed
         Pregunt p=new Pregunt();
        p.setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_pdanActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
      Buscar b= new Buscar();
      b.setVisible(true);
      this.setVisible(false);
      this.dispose();
    }//GEN-LAST:event_buscarActionPerformed

    private void sdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdanActionPerformed
         Pregunt p=new Pregunt();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sdanActionPerformed

    private void tdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdanActionPerformed
       Pregunt p=new Pregunt();
        p.setVisible(true);  
        this.setVisible(false);
    }//GEN-LAST:event_tdanActionPerformed

    private void primerdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primerdanActionPerformed
      Cuestionario2 c= new Cuestionario2();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_primerdanActionPerformed

    private void tercerdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tercerdanActionPerformed
       Cuestionario4 c= new Cuestionario4();
        c.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_tercerdanActionPerformed

    private void cinnegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinnegroActionPerformed
        Cuestionario c= new Cuestionario();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cinnegroActionPerformed

    private void segundodanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundodanActionPerformed
       Cuestionario3 c= new Cuestionario3();
        c.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_segundodanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AspiranteDan;
    private javax.swing.JMenuItem CRequisitor;
    private javax.swing.JMenu Cuestionario;
    private javax.swing.JMenuItem Estudiantes;
    private javax.swing.JMenuItem Examen;
    private javax.swing.JMenu Inscripcion;
    private javax.swing.JMenuItem Instructor;
    private javax.swing.JLabel JPG;
    private javax.swing.JMenu Registro;
    private javax.swing.JMenu abriCues;
    private javax.swing.JMenuItem buscar;
    private javax.swing.JMenuItem cinnegro;
    private javax.swing.JMenuItem cnegro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem pdan;
    private javax.swing.JMenuItem primerdan;
    private javax.swing.JMenuItem sdan;
    private javax.swing.JMenuItem segundodan;
    private javax.swing.JMenuItem tdan;
    private javax.swing.JMenuItem tercerdan;
    // End of variables declaration//GEN-END:variables
}
