
package menuk;


import Inscripcion.*;
import static Inscripcion.Estudiante.isInt;
import static Inscripcion.Inscripcion.BuscarEstud;
import static Inscripcion.OperacionEstudiante.BuscarEstudiante;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import ventanas.*;

public class VentanaExamen extends javax.swing.JFrame {

   
    public VentanaExamen() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
            setResizable(false);
            setTitle("Examen");
            setIconImage(new ImageIcon(getClass().getResource("/imagenes/Icono.PNG")).getImage());
        cintanegra.setEnabled(false);
        primerdam.setEnabled(false);
        segundodam.setEnabled(false);
        tercerdam.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cintanegra = new javax.swing.JButton();
        primerdam = new javax.swing.JButton();
        segundodam = new javax.swing.JButton();
        tercerdam = new javax.swing.JButton();
        menuExamen = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        cedprue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        regre = new javax.swing.JButton();
        ingreprue = new javax.swing.JButton();
        Lnivel = new javax.swing.JLabel();
        Lnomb = new javax.swing.JLabel();
        nomIn = new javax.swing.JLabel();
        Lnomb1 = new javax.swing.JLabel();
        Lnivel1 = new javax.swing.JLabel();
        nomIn1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Seleccion de Categoría");
        setType(java.awt.Window.Type.POPUP);

        cintanegra.setText("CINTURÓN NEGRO");
        cintanegra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cintanegraActionPerformed(evt);
            }
        });

        primerdam.setText("PRIMER DAN");
        primerdam.setPreferredSize(new java.awt.Dimension(136, 26));
        primerdam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primerdamActionPerformed(evt);
            }
        });

        segundodam.setText("SEGUNDO DAN");
        segundodam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundodamActionPerformed(evt);
            }
        });

        tercerdam.setText("TERCER DAN");
        tercerdam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tercerdamActionPerformed(evt);
            }
        });

        menuExamen.setBackground(new java.awt.Color(96, 130, 166));
        menuExamen.setForeground(new java.awt.Color(51, 0, 51));
        menuExamen.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);

        jLabel1.setFont(new java.awt.Font("Super Street Fighter Hyper Font", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Bienvenido al Examen de la Federacion Madrileña de Karate");

        cedprue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedprueActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Digite su numero de Cedula");

        regre.setText("Regresar");
        regre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regreActionPerformed(evt);
            }
        });

        ingreprue.setText("Ingresar");
        ingreprue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreprueActionPerformed(evt);
            }
        });

        Lnivel.setBackground(new java.awt.Color(0, 153, 153));
        Lnivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Lnivel.setText("Nivel");

        Lnomb.setBackground(new java.awt.Color(0, 153, 204));
        Lnomb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Lnomb.setText("Nombre");

        nomIn.setBackground(new java.awt.Color(0, 102, 102));
        nomIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nomIn.setText("Nombre Instructor");

        Lnomb1.setBackground(new java.awt.Color(0, 153, 204));
        Lnomb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Lnomb1.setText("Nombre:");

        Lnivel1.setBackground(new java.awt.Color(0, 153, 153));
        Lnivel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Lnivel1.setText("Nivel:");

        nomIn1.setBackground(new java.awt.Color(0, 102, 102));
        nomIn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nomIn1.setText("Nombre del Instructor:");

        menuExamen.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        menuExamen.setLayer(cedprue, javax.swing.JLayeredPane.DEFAULT_LAYER);
        menuExamen.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        menuExamen.setLayer(regre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        menuExamen.setLayer(ingreprue, javax.swing.JLayeredPane.DEFAULT_LAYER);
        menuExamen.setLayer(Lnivel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        menuExamen.setLayer(Lnomb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        menuExamen.setLayer(nomIn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        menuExamen.setLayer(Lnomb1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        menuExamen.setLayer(Lnivel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        menuExamen.setLayer(nomIn1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout menuExamenLayout = new javax.swing.GroupLayout(menuExamen);
        menuExamen.setLayout(menuExamenLayout);
        menuExamenLayout.setHorizontalGroup(
            menuExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuExamenLayout.createSequentialGroup()
                .addGroup(menuExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuExamenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(regre))
                    .addGroup(menuExamenLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cedprue, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(ingreprue))
                    .addGroup(menuExamenLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuExamenLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(menuExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuExamenLayout.createSequentialGroup()
                                .addComponent(nomIn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomIn))
                            .addGroup(menuExamenLayout.createSequentialGroup()
                                .addGroup(menuExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Lnomb1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lnivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(menuExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lnivel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lnomb, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuExamenLayout.setVerticalGroup(
            menuExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuExamenLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(menuExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingreprue)
                    .addComponent(cedprue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addGroup(menuExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lnomb, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lnomb1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lnivel)
                    .addComponent(Lnivel1))
                .addGap(27, 27, 27)
                .addGroup(menuExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomIn1)
                    .addComponent(nomIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(regre)
                .addContainerGap())
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cintanegra, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(primerdam, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(segundodam, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tercerdam, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(menuExamen)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primerdam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(segundodam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tercerdam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cintanegra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void primerdamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primerdamActionPerformed
    PrimerDAN ot=new PrimerDAN();
    ot.setVisible(true);
     if(!(ot.isActive())){
        primerdam.setEnabled(false);
        }
    }//GEN-LAST:event_primerdamActionPerformed

    private void cintanegraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cintanegraActionPerformed
       CinturonNegro ot=new CinturonNegro();
        ot.setVisible(true);
        this.setVisible(false);
        this.dispose();
        
        cedprue.getText();
        if(!(ot.isActive())){
        cintanegra.setEnabled(false);
        }
    }//GEN-LAST:event_cintanegraActionPerformed

    private void segundodamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundodamActionPerformed
        SegundoDAN ot=new SegundoDAN();
        ot.setVisible(true);
        if(!(ot.isActive())){
        segundodam.setEnabled(false);
        }
    }//GEN-LAST:event_segundodamActionPerformed

    private void tercerdamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tercerdamActionPerformed
        TercerDAN ot=new TercerDAN();
        ot.setVisible(true);
        if(!(ot.isActive())){
        tercerdam.setEnabled(false);
        }
    }//GEN-LAST:event_tercerdamActionPerformed

    private void regreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regreActionPerformed
      Interface A=new Interface();
        A.setVisible(true);
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_regreActionPerformed

    private void ingreprueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreprueActionPerformed
        if(cedprue.getText().isEmpty()){
       JOptionPane.showMessageDialog(rootPane,"Ingrese Numero de Cedula");
        if( cedprue.getText().length()==10 && isInt(cedprue.getText())){
            
           
         
        }else{
         JOptionPane.showMessageDialog(rootPane,"Ingrese Una Cedula Valida");}
       }
       else{ Inscripcion leer = new Inscripcion();
         Estudiante es=new Estudiante();
        try{
            es= BuscarEstudiante(cedprue.getText());
            leer = BuscarEstud(cedprue.getText().trim());
        }catch(IOException ex){
            Logger.getLogger(VentanaInscripcion.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane,"UD NO SE ENCUENTRA INSPCRITO");
        }
         Estudiante ot= new Estudiante();
         ot.setCedula(cedprue.getText());
         ot.setApellido(es.getApellido());
        ot.setDireccion(es.getDireccion());
        ot.setTelefono(es.getTelefono());
        ot.setEdad(es.getEdad());
        ot.setNivel(es.getNivel());
         ot.setNombre(es.getNombre());
         
        Lnomb.setText(leer.getNombre());
        Lnivel.setText(leer.getNivel());
        nomIn.setText(leer.getIns());
        switch (leer.getNivel()){
                case "Dan 1": cintanegra.setEnabled(true);
                break;
                case "Dan 2": primerdam.setEnabled(true);
                break;
                case "Dan 3": segundodam.setEnabled(true);
                break;
                case "Dan 4": tercerdam.setEnabled(true);}
         
       }
    }//GEN-LAST:event_ingreprueActionPerformed

    private void cedprueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedprueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedprueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaExamen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lnivel;
    private javax.swing.JLabel Lnivel1;
    private javax.swing.JLabel Lnomb;
    private javax.swing.JLabel Lnomb1;
    private javax.swing.JTextField cedprue;
    private javax.swing.JButton cintanegra;
    private javax.swing.JButton ingreprue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane menuExamen;
    private javax.swing.JLabel nomIn;
    private javax.swing.JLabel nomIn1;
    private javax.swing.JButton primerdam;
    private javax.swing.JButton regre;
    private javax.swing.JButton segundodam;
    private javax.swing.JButton tercerdam;
    // End of variables declaration//GEN-END:variables
}
